[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "printbench"
version = "0.1.0"
description = "Framework for generating and analyzing print characterization targets."
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Mike Guyre" }
]
keywords = [
    "printing",
    "calibration",
    "svg",
    "png",
    "image-analysis",
    "metrology"
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "black",
]

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]